// Code generated by "packer-sdc mapstructure-to-hcl2"; DO NOT EDIT.

package aap

import (
	"github.com/hashicorp/hcl/v2/hcldec"
	"github.com/zclconf/go-cty/cty"
)

// FlatConfig is an auto-generated flat version of Config.
// Where the contents of a field with a `mapstructure:,squash` tag are bubbled up.
type FlatConfig struct {
	AAPUrl            *string           `mapstructure:"aap_url" required:"true" cty:"aap_url" hcl:"aap_url"`
	AAPUsername       *string           `mapstructure:"aap_username" required:"true" cty:"aap_username" hcl:"aap_username"`
	AAPPassword       *string           `mapstructure:"aap_password" required:"true" cty:"aap_password" hcl:"aap_password"`
	CreateInventory   *bool             `mapstructure:"create_inventory" cty:"create_inventory" hcl:"create_inventory"`
	InventoryName     *string           `mapstructure:"inventory_name" cty:"inventory_name" hcl:"inventory_name"`
	InventoryDesc     *string           `mapstructure:"inventory_description" cty:"inventory_description" hcl:"inventory_description"`
	OrganizationID    *int              `mapstructure:"organization_id" cty:"organization_id" hcl:"organization_id"`
	ExistingInventory *int              `mapstructure:"existing_inventory_id" cty:"existing_inventory_id" hcl:"existing_inventory_id"`
	CreateHost        *bool             `mapstructure:"create_host" cty:"create_host" hcl:"create_host"`
	HostName          *string           `mapstructure:"host_name" cty:"host_name" hcl:"host_name"`
	HostDescription   *string           `mapstructure:"host_description" cty:"host_description" hcl:"host_description"`
	HostVariables     map[string]string `mapstructure:"host_variables" cty:"host_variables" hcl:"host_variables"`
	AddToInventory    *bool             `mapstructure:"add_host_to_inventory" cty:"add_host_to_inventory" hcl:"add_host_to_inventory"`
	RunJobTemplate    *bool             `mapstructure:"run_job_template" cty:"run_job_template" hcl:"run_job_template"`
	JobTemplateID     *int              `mapstructure:"job_template_id" cty:"job_template_id" hcl:"job_template_id"`
	JobLimit          *string           `mapstructure:"job_limit" cty:"job_limit" hcl:"job_limit"`
	JobExtraVars      map[string]string `mapstructure:"job_extra_vars" cty:"job_extra_vars" hcl:"job_extra_vars"`
}

// FlatMapstructure returns a new FlatConfig.
// FlatConfig is an auto-generated flat version of Config.
// Where the contents a fields with a `mapstructure:,squash` tag are bubbled up.
func (*Config) FlatMapstructure() interface{ HCL2Spec() map[string]hcldec.Spec } {
	return new(FlatConfig)
}

// HCL2Spec returns the hcl spec of a Config.
// This spec is used by HCL to read the fields of Config.
// The decoded values from this spec will then be applied to a FlatConfig.
func (*FlatConfig) HCL2Spec() map[string]hcldec.Spec {
	s := map[string]hcldec.Spec{
		"aap_url":               &hcldec.AttrSpec{Name: "aap_url", Type: cty.String, Required: false},
		"aap_username":          &hcldec.AttrSpec{Name: "aap_username", Type: cty.String, Required: false},
		"aap_password":          &hcldec.AttrSpec{Name: "aap_password", Type: cty.String, Required: false},
		"create_inventory":      &hcldec.AttrSpec{Name: "create_inventory", Type: cty.Bool, Required: false},
		"inventory_name":        &hcldec.AttrSpec{Name: "inventory_name", Type: cty.String, Required: false},
		"inventory_description": &hcldec.AttrSpec{Name: "inventory_description", Type: cty.String, Required: false},
		"organization_id":       &hcldec.AttrSpec{Name: "organization_id", Type: cty.Number, Required: false},
		"existing_inventory_id": &hcldec.AttrSpec{Name: "existing_inventory_id", Type: cty.Number, Required: false},
		"create_host":           &hcldec.AttrSpec{Name: "create_host", Type: cty.Bool, Required: false},
		"host_name":             &hcldec.AttrSpec{Name: "host_name", Type: cty.String, Required: false},
		"host_description":      &hcldec.AttrSpec{Name: "host_description", Type: cty.String, Required: false},
		"host_variables":        &hcldec.AttrSpec{Name: "host_variables", Type: cty.Map(cty.String), Required: false},
		"add_host_to_inventory": &hcldec.AttrSpec{Name: "add_host_to_inventory", Type: cty.Bool, Required: false},
		"run_job_template":      &hcldec.AttrSpec{Name: "run_job_template", Type: cty.Bool, Required: false},
		"job_template_id":       &hcldec.AttrSpec{Name: "job_template_id", Type: cty.Number, Required: false},
		"job_limit":             &hcldec.AttrSpec{Name: "job_limit", Type: cty.String, Required: false},
		"job_extra_vars":        &hcldec.AttrSpec{Name: "job_extra_vars", Type: cty.Map(cty.String), Required: false},
	}
	return s
}
